### ISSUE TITLE
Technical Data Version 1.2 plugin missing in AASX Package Explorer V3 2023-11-17.alpha

### ISSUE THREAD

**Issue by JS-Aibel** [eclipse-aaspe/aaspe#10]
**Describe the bug**
Technical Data Version 1.2 plugin missing in AASX Package Explorer V3 2023-11-17.alpha.

**To Reproduce**
When creating a TechnicalData submodel in the Package Explorer from “New submodel from plugin”, I only get the option to choose Technical Data Version 1.0 or Version 1.1.

**Expected behavior**
According to [Technical_Data/1/2](https://github.com/admin-shell-io/submodel-templates/tree/main/published/Technical_Data/1/2), version 1.2 is “in productive use and supported by AASX Package Explorer (out of the box).”

**Comment by MichaelHoffmeisterFesto** [comment]
Current branch name: MIHO/Post_XMAS2023_Bugfixes

* see also: https://github.com/eclipse-aaspe/aaspe/issues/193
* using "Workspace / Create / New Submodel from plugin .. " now provides a V1.2 option.
