### ISSUE TITLE
Links to Contribution Guide do not work any longer

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-aaspe/aaspe#102]
Links to Contribution Guide do not work any longer

https://github.com/admin-shell-io/aasx-package-explorer/blob/master/docdev/docfx_project/getting-started/intro.md

**Comment by juileetikekar** [comment]
Hi @BirgitBoss,

Please find the updated contributing guidelines at https://github.com/eclipse-aaspe/aaspe/blob/main/CONTRIBUTING.md.
