### ISSUE TITLE
ConceptDescription cannot be looked up within the AAS environment!

### ISSUE THREAD

**Issue by JS-Aibel** [eclipse-aaspe/aaspe#11]
**Describe the bug**
When creating a property with a reference to a ConceptDescription, the ConceptDescription does not come up in the property. A label saying “_ConceptDescription cannot be looked up within the AAS environment!_“ is shown.
To get the correct behavior, I need to manually assign the ConceptDescription.

**To Reproduce**
1.	Create a property.
2.	In the “**Editing of entities**” for the property, click **Concept Description: “Create empty”** button.
3.	A Concept Description and a corresponding semantic id reference on the property will be created.
4.	Label in the property saying: “_ConceptDescription cannot be looked up within the AAS environment!_“.
5.	In the “**Editing of entities**” for the property click **Concept Description: “Use existing”** button.
6.	Navigate to the desired ConceptDescription and select it in the menu.
7.	The property will show the ConceptDescription as expected.

**Expected behavior**
When a property has a semantic id to a ConceptDescription, it should not be needed to manually assign it.
This [screencast](https://admin-shell-io.com/screencasts/aasx-package-explorer/en/Aasx_PackEx_Tutorial_-_EN_-_09_Create_a_SubmodelElement_and_a_ConceptDescription.mp4) shows the expected behavior.

**Why is this a problem**
It is too cumbersome to have to manually reselect Concept Descriptions for every property.

**Comment by JS-Aibel** [comment]
I figured out what triggers it. 
When creating a Concept Description from the **“Create empty”** button on the property, the semantic id reference on the property becomes a **“ModelReference”**. If I switch the semantic id to **“ExternalReference”**, the Concept Description is shown in the Property as expected.

**Comment by juileetikekar** [comment]
HI @JS-Aibel,

Thank you for raising the issue !!

The described behavior was succeessfully reproduced. We will keep you updated further.
