### ISSUE TITLE
CSV-Import doesn't work for certain setups

### ISSUE THREAD

**Issue by Hautonom** [eclipse-aaspe/aaspe#111]
Hello,

I try to insert data from csv-files, but it doesn't work. The screencast example does not work for me too. However your example from admin-shell-io/temp-aasx-package-explorer#52 works seamlessly. But as soon as I add a new column / metadata (e. g. semanticID) it fails. I tried the following without success:

- Different metadata as additional
- Replace "value" with other metadata

I have no C# experience so debugging would be heavily time consuming. Hopefully you have an idea.
Thanks in advance!

**Comment by juileetikekar** [comment]
Hi @Hautonom ,

Please refer the comment #[https://github.com/eclipse-aaspe/aaspe/issues/141 issue](https://github.com/eclipse-aaspe/aaspe/issues/141#issuecomment-1991495468) for more details.

Also, I would like to request you to use the latest version of the AASX Package Explorer, as it now supports the latest version of AAS Metamodel V3.0.
