### ISSUE TITLE
AASX Package Explorer cannot open AAS JSON based on data model V3

### ISSUE THREAD

**Issue by matthias-tn** [eclipse-aaspe/aaspe#117]
An exception occurs if you try to open an AAS JSON in AASX Package Explorer which is based on AAS data model spec V3. The problem is that according to spec V3 the submodel valueType is just a string attribute e.g. `"valueType:""string"`. The AASX Package Explorer expects an object like:

```
"valueType": {
      "dataObjectType": {
        "name": "string"
      }
 }
```

The same problem applies also to AAS XML files which are based on latest (V3) AAS.xsd
see also "valueType" definition here:
https://github.com/admin-shell-io/aas-specs/blob/V3.0.3RC01/schemas/xml/AAS.xsd

***Exception***

`InnerException: While opening aasx C:\Users\MatthiasMaier\Desktop\01_Festo.json from source local file: C:\Users\MatthiasMaier\Desktop\01_Festo.json at \AdminShellPackageEnv.cs:Zeile 304. gave: While reading AAS C:\Users\MatthiasMaier\Desktop\01_Festo.json at \AdminShellConverters.cs:Zeile 98. gave: Error converting value "string" to type 'AdminShellNS.AdminShellV20+JsonValueTypeCast'. Path 'valueType', line 198, position 31. at    bei AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:Zeile 104.
   bei AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:Zeile 293.
   bei AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__4.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:Zeile 140.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).`

**To Reproduce**

1. Go to 'File -> Open'
2. Open an AAS JSON or XML based on AAS spec V3
3. See error

**Comment by juileetikekar** [comment]
Hi @matthias-tn,

Please use the latest version of the AASX Package Explorer, which now supports the AAS metamodel V3.0. This version can deserialize valueType successfully.
