### ISSUE TITLE
Crashes when opening V3

### ISSUE THREAD

**Issue by felix-schubert** [eclipse-aaspe/aaspe#119]
When opening an aasx package or xml-file build according to V3 of the specs, I get a silent crash.
I would prefer an error message, telling me that the operation failed. Ideally stating, that V3 is not yet supported.

**Comment by juileetikekar** [comment]
Hi @felix-schubert,

I would like to request you to try the latest version of the AASX Package Explorer, which now supports the AAS Metamodel V3.0.
