### ISSUE TITLE
Error occurs when importing Submodels/SubModelElements exported from iec-cdd.

### ISSUE THREAD

**Issue by JS-Aibel** [eclipse-aaspe/aaspe#12]
**Describe the bug**
Not able to import Submodels/SubModelElements exported from iec-cdd.
Aasx Package Explorer v3 Version v2023-11-17

**To Reproduce**
By following this screencast [Import_IEC_CDD_Class_Export](https://admin-shell-io.com/screencasts/aasx-package-explorer/en/Aasx_PackEx_Tutorial_-_EN_-_52_Import_IEC_CDD_Class_Export.mp4)

1. Download **iec-cdd excel-files**
2. Place them in a folder `AasxPackageExplorer\iec-cdd\export 2024-01-01`
1. Select an AAS in Package Explorer
3. Import Submodel from Dictionary
4. Select the iec-cdd **“Source”** in the **“Dictionary Import”** menu, an error occurs.
5. See error

Same error messages occurs when importing as SubModelElements.

**Error**

> Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: No data is available for encoding 1252.
> For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. at    at System.Text.Encoding.GetEncoding(Int32 codepage)   at ExcelDataReader.ExcelReaderConfiguration..ctor()   at ExcelDataReader.ExcelReaderFactory.CreateReader(Stream fileStream, ExcelReaderConfiguration configuration)...

**Comment by juileetikekar** [comment]
Hi @JS-Aibel,

Thank you for raising the issue !!

The issue was reproduced. We will keep you informed about further updates.
