### ISSUE TITLE
How to add a specificassetid to the assetInformation

### ISSUE THREAD

**Issue by vChavezB** [eclipse-aaspe/aaspe#122]
I am still quite new to the asset administration shell and I am reading the spec. The issue at hand is that I havent found a way to add instances of the `specificAssetId `to the class `AssetInformation `seen in Figure 23 of the latest spec (v3).

**Comment by juileetikekar** [comment]
Hi @vChavezB,

With respect to the latest version of the AASX Package Explorer, below are the steps to add a SpecificAssetId to the AssetInformation:

1. Create an AAS
2. In the end of the right/editing panel of the AAS, there is a section for AssetInformation.
3. In front of SpecificAssetId, click on "Create data element".
4. Cklick on "Add blank", "Add preset" or "Add from clipboard" as required.

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/23287567-c2ff-46bb-b3a9-0fb530a952bc)

**Comment by vChavezB** [comment]
Thanks for the update.
