### ISSUE TITLE
Plan for AAS spec version 3

### ISSUE THREAD

**Issue by ketiiot** [eclipse-aaspe/aaspe#127]
Hello,

According to the previous conversation at the issu admin-shell-io/temp-aasx-package-explorer#44, AASX will support V3.0 at the beginning of 2022. 
But the AAS spec version 2.0 is still used in the AASX package explorer.  Do you have a plan for this?

Thank you.

**Comment by juileetikekar** [comment]
Hi @ketiiot and @hmrc87,

The latest version of the AASX Package Explorer supports the AAS Metamodel V3.0.
