### ISSUE TITLE
No possibility to add an eclass license

### ISSUE THREAD

**Issue by Deputy-Chief-Hardy** [eclipse-aaspe/aaspe#128]
**Describe the bug**
I wanted to to imitate the screencast "AASX PackEx Tutorial - EN - 53 Import ECLASS Class Webservice", but there is no possibility to add an eclass license.

**To Reproduce**
1. Go to 'File' --> 'Import' --> 'Import Submodel from Dictionary'
2. Click on 'Fetch Online'
3. Type in one of the given examples and click 'OK'
4. See Fetch Error: Could not fetch the requested data. Details: No valid ECLASS certificate selected

**Expected behavior**
In the screencast there is the possibility to add an eclass license or to choose a test license.

**Screenshots**
![Fehlermeldung AASX Package Explorer](https://user-images.githubusercontent.com/49750085/211508644-a26e2b8d-ce5e-480a-9c31-0db92b13d3a3.PNG)

**Desktop:**
 - OS: Windows
 - AASX Package Explorer Version v2022-08-06

**Comment by juileetikekar** [comment]
Hi @Deputy-Chief-Hardy,

We hope that the hint provided above has worked with you. In case of further, issues please feel free to raise an issue.
