### ISSUE TITLE
JSON Schema export for TechnicalData is invalid

### ISSUE THREAD

**Issue by shuebner** [eclipse-aaspe/aaspe#130]
**Describe the bug**
From the submodel template for TechnicalData, a JSON Schema will be exported with `"allOf": []`, which is invalid according to the JSON Schema Spec 2019-09. See [here](https://json-schema.org/draft/2019-09/meta/applicator), l. 44.

**To Reproduce**
1. Open [the submodel template for TechnicalData V1.2](https://github.com/admin-shell-io/submodel-templates/blob/main/published/Technical_Data/1/2/IDTA%2002003-1-2_SubmodelTemplate_TechnicalData_v1.2_withQualifier.aasx)
2. Click on File --> Export --> Export Submodel JSON Schema
3. The error is in l. 763, which is 4th-to-last line in the following:

```json
    "SubSection": {
      "properties": {
        "idShort": {
          "const": "SubSection"
        },
        "kind": {
          "const": "Instance"
        },
        "modelType": {
          "properties": {
            "name": {
              "const": "SubmodelElementCollection"
            }
          }
        },
        "semanticId": {
          "properties": {
            "keys": {
              "type": "array",
              "allOf": [
                {
                  "contains": {
                    "properties": {
                      "type": {
                        "const": "GlobalReference"
                      },
                      "local": {
                        "const": false
                      },
                      "value": {
                        "const": "https://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1"
                      },
                      "idType": {
                        "const": "IRI"
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        "value": {
          "type": "array",
          "allOf": []
        }
      }
    }
```

**Expected behavior**
As far as I understand AAS, since the SMC "SubSection" is defined with no elements, it should result in a schema definition for an empty array.

I do not understand why such a thing was declared in TechnicalData in the first place.
Maybe the AAS definition must be changed as well.

**Comment by juileetikekar** [comment]
Hi @shuebner,

The issue has been fixed in the latest version of the AASX Package Explorer, which also supports the V3 version of the AAS Metamodel.

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/b84a72c2-3db1-4e98-adeb-e03dce5c0125)
