### ISSUE TITLE
DocumentShelf 'Add Document ..' broken

### ISSUE THREAD

**Issue by cabuchan** [eclipse-aaspe/aaspe#131]
**Description**
I am unable to add a document to the document shelf using the 'Add Document ..' in the top right corner of the Document Shelf. This is the same for both the recommended version and the development version. 

**To Reproduce**
1. Click on the AAS
2. Click on Workspace -> Plugins -> New Submodel
3. Select 'Document (recommended version)' or 'Document (development version V1.1)'
4. Open Document Shelf
5. Select 'Add Document ..'
6. See error as nothing comes up

**Expected behavior**
I expected the form to add a document to show.

**Desktop:**
 - OS: [e.g. Windows]
 - Version [2023-02-03.alpha]

**Comment by juileetikekar** [comment]
Hi @cabuchan and @XentechTips,

The issu has been fixed in the latest version of the AASX Package Explorer. This latest version also supports the latest V3 version of the AAS Metamodel.
