### ISSUE TITLE
aasx non-importable in AAS4J due to not-schema-compliant xml

### ISSUE THREAD

**Issue by keiligch** [eclipse-aaspe/aaspe#134]
**Description**
_Used Package Explorer version is v2023-02-03._

When creating an AAS with the Package Explorer, the aasx-file is not importable in AAS4J due to mistakes in the xml-file within the .aasx.

- Example 1: when the SemanticId of the Submodel is not set in the package explorer, the xml contains

```
<aas:submodel>
  [...]
  <aas:semanticId>
    <aas:keys />
  </aas:semanticId>
```
, leading to an serialization exception in java while importing with AAS4j due to the empty `keys`-element.

- Example 2: the submodel elements in the xml are structured as follows:

```
<aas:submodelElements>
   <aas:submodelElement>
     <aas:property>
```
. The `<aas:submodelElement>`-element is not compliant to the schema, it must be 
```
<aas:submodelElements>
  <aas:property>
```
.

**To Reproduce**

1. Create new AAS with the Package Explorer, adding a _submodel_ without a _semanticId_
2. Adding a _property_
3. Save as .aasx 
4. Setup a new Java-Project and set AAS4J as a dependency
5. use the aasx-file as an InputStream as an argument for the AASXDeserializer constructor
6. run the read()-method on the AASXDeserializer-object.
7. get Exceptions related to Example 1
8. remove semanticId- and keys-elements from xml
9. run AASXDeserializer again
10. get Exceptions related to Example 2
11. remove submodelElement-element 
12. run AASXDeserializer again successfully

**Comment by juileetikekar** [comment]
Hi @keiligch,

The issue with empty lists has already been fixed in the latest version of the AASX Package Explorer.
