### ISSUE TITLE
ASSX Package Explorer runnable on MacOS

### ISSUE THREAD

**Issue by joaquinse-xitaso** [eclipse-aaspe/aaspe#140]
**Is your feature request related to a problem? Please describe.**
The app is not runnable on MacOS

**Describe the solution you'd like**
I would like it to be runnable on MacOS

**Describe alternatives you've considered**
The alternatives would be using a Windows emulator.

**Comment by juileetikekar** [comment]
Hi @joaquinse-xitaso,

Please try the Blazor version of the AASPE.
