### ISSUE TITLE
Import of csv files not possible?!

### ISSUE THREAD

**Issue by TobiLausH** [eclipse-aaspe/aaspe#141]
I tried to import a csv file into my AAS. I proceeded as shown in the screencast for the asset administration shell. There is also no error displayed. The submodel simply does not fill. 

Does anyone else here have this problem and can help me?

Many greetings
Tobi

**Comment by juileetikekar** [comment]
Hi @TobiLausH,

Please follow below steps in AASPE to import the CSV based submodel elements:

1. Create an AASX File consisting of an AAS and an empty submodel.
2. Save the file.
3. Open the file again in AASPE (this step opens the file in **non-edit** mode)
4. Click on the empty submodel
5. Now go to File-> Import -> Import CSV-file into SubModel
6. Select the CSV file
7. Save the file again
8. Now, you should be able to see the submodel elements.

### Please Note: The column titles are case and order sensitive. Please make sure, the CSV consists of below column titles:
1. typeName
2. idShort
3. value
4. valueType
5. category
6. descriptionEN
7. descriptionDE
8. semanticId

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/7ae4e642-fffa-4c46-a93b-60ae9008a60c)
