### ISSUE TITLE
BUG xml Drag&Drop IEC61360 Data Specification

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-aaspe/aaspe#155]
**Describe the bug**
When importing the file attached via Drag&Drop into the aasx package explorer (version v2023-09-12) then the fields for the data specification are not visible

**To Reproduce**
1. importing file attached via Drag&Drop (rename .xml not supported in issue, so remove .txt)

[Batch-aas;5.xml.txt](https://github.com/admin-shell-io/aasx-package-explorer/files/13025222/Batch-aas.5.xml.txt)

3. Switch On Edit Mode
4. Go to Concept Descriptions, first CD with idShort "id_Batch" and id "urn:samm:io.catenax.batch:2.0.0#Batch"
5. Go to "HasDataSpecification"

![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/59824205/deaade81-a85e-45c9-b559-e609a7b1c117)
6. Click on "IEC61360" and delete the first one: 

![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/59824205/9070b6e8-a682-45d4-a3fe-8cd9a243f831)

7. now information from file is available:
![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/59824205/b11edf75-57c1-4f33-ad9b-e9961495fd81)

**Expected behavior**
show data specification at once

**Comment by juileetikekar** [comment]
The issue is not reproducible in the latest version.
