### ISSUE TITLE
DataSpecification not shown after loading AASX created in PE 2x into PE 3

### ISSUE THREAD

**Issue by foprs** [eclipse-aaspe/aaspe#157]
After loading the aasx-file that has been create with an ealier version into PE 3, the DataSpec. is not shown anymore. The unit is shown at the property submodel element. That means the information is still existing.

![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/118162568/1a2e0058-01b8-4096-b4f0-1875adf518a7)
[Technical_Data_LGM_v2.zip](https://github.com/admin-shell-io/aasx-package-explorer/files/13070125/Technical_Data_LGM_v2.zip)

**Comment by juileetikekar** [comment]
Hi @foprs ,

Thank you for raising the issue !!

The issue has been reproduced and we are working on it. We will keep you informed once it is fixed.
