### ISSUE TITLE
Wrong relationship type in the package xml files

### ISSUE THREAD

**Issue by quickhdsdcIPA** [eclipse-aaspe/aaspe#172]
Hi, I notice the latest release [AASX Package Explorer V3 2023-11-17.alpha] still creates AASX file with old relationship types.
RELATIONSHIP_TYPE_AASX_ORIGIN = "http://www.admin-shell.io/aasx/relationships/aasx-origin"
RELATIONSHIP_TYPE_AAS_SPEC = "http://www.admin-shell.io/aasx/relationships/aas-spec"
RELATIONSHIP_TYPE_AAS_SPEC_SPLIT = "http://www.admin-shell.io/aasx/relationships/aas-spec-split"
RELATIONSHIP_TYPE_AAS_SUPL = "http://www.admin-shell.io/aasx/relationships/aas-suppl"

The new one should be 
RELATIONSHIP_TYPE_AASX_ORIGIN = "http://admin-shell.io/aasx/relationships/aasx-origin"
RELATIONSHIP_TYPE_AAS_SPEC = "http://admin-shell.io/aasx/relationships/aas-spec"
RELATIONSHIP_TYPE_AAS_SPEC_SPLIT = "http://admin-shell.io/aasx/relationships/aas-spec-split"
RELATIONSHIP_TYPE_AAS_SUPL = "http://admin-shell.io/aasx/relationships/aas-suppl"

**Comment by WelliSolutions** [comment]
The latest release is 2024-02-27. Find it [in the old repo under Releases](https://github.com/admin-shell-io/aasx-package-explorer/releases).

**Comment by quickhdsdcIPA** [comment]
Thank you!
