### ISSUE TITLE
Check, validate and fix

### ISSUE THREAD

**Issue by jaalvarado20** [eclipse-aaspe/aaspe#179]
**Describe the bug**
Is there a problem with "Check, validate and fix" button?

**To Reproduce**
1. Create an AAS'
2. Create a Sumbodel
3. Save
4. Go to file, then check, validate an fix

**Screenshots**
![image](https://github.com/eclipse-aaspe/aaspe/assets/73915924/bfbe759b-70ca-4b49-b5eb-834a2692f4ab)
![image](https://github.com/eclipse-aaspe/aaspe/assets/73915924/294ba632-12fb-4777-bfc7-6e92fadf205c)

Thanks!!

**Comment by juileetikekar** [comment]
Hi @jaalvarado20,

Thank you for raising the issue !!

Is it possible to share the AASX File with us to debug the issue further?

**Comment by jaalvarado20** [comment]
Hi, 
I can´t send the .aasx File, but i´m attaching the Json file:

[MyFirstAAS.json](https://github.com/eclipse-aaspe/aaspe/files/14507007/MyFirstAAS.json)

**Comment by jaalvarado20** [comment]
Additionaly, I ciuld save the AAS file without errors, but when i saved it like JSON file, this error appears....
![image](https://github.com/eclipse-aaspe/aaspe/assets/73915924/d2f8bf00-a106-424f-a7e8-7e61b8fe5282)
