### ISSUE TITLE
v2024-03-05.alpha release reintroduces bug that was fixed in v2024-02-27.alpha

### ISSUE THREAD

**Issue by FrankSchnicke** [eclipse-aaspe/aaspe#184]
The v2024-03-05.alpha release is using the wrong namespace "http://www.admin-shell.io/aasx/relationships/aasx-origin" again instead of "http://admin-shell.io/aasx/relationships/aasx-origin". This was fixed in v2024-02-27.alpha but now popped up again.

1. Create arbitrary AASX with AASPE
2. Take a look at _rels/.rels within AASX file
3. See wrong namespace: "<Relationship Type="http://www.admin-shell.io/aasx/relationships/aasx-origin ..."

Additionally, the AASPE is not not able any more to load AASX files with the correct namespace which was possible in the previous release.

**Expected behavior**
Use the correct namespace and being able to load an AASX file using the correct namespace.

**Comment by juileetikekar** [comment]
Hi @FrankSchnicke,

Thank you for bringing this to our notice !! 

The fix was provided on admin-shell-io repo and the corresponding commit now needs to be manually added to the eclipse repo. The team has already been informed about this and is working on it.

**Comment by juileetikekar** [comment]
PR #185 closes this issue.
