### ISSUE TITLE
Handover Documentation 1.2 Plugin

### ISSUE THREAD

**Issue by WelliSolutions** [eclipse-aaspe/aaspe#192]
**Is your feature request related to a problem? Please describe.**
I am trying to create an AASX with documentation according to the IDTA-02004-1-2 Handover Documentation submodel specification.
Currently, Package Explorer only has plugins for the development version 1.0 and 1.1 of that submodel.

**Describe the solution you'd like**
Update the plugin to the official version 1.2

**Describe alternatives you've considered**
Using the old 1.0 and 1.1 versions - but they are development versions only and not officially released.

**Additional context**
Version 1.2 should use semantic ID `0173-1#01-AHF578#001` instead of `https://admin-shell.io/vdi/2770/1/1/Documentation`

**Comment by juileetikekar** [comment]
Hi @WelliSolutions,

The latest version of the AASX Package Explorer supports the Handover Documentation Submodel with version V1.2, icluding the semanticId "0173-1#01-AHF578#001".

Below are three ways to handle "Handover Documentation V1.2":
**1. Create a SM from plugin**
       Workspace -> Create -> New Submodel from Plugin
       The generated submodel consists of document shelf, handover documentation form and has a semanticId "0173-1#01-AHF578#001"
       
![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/1fde5e9e-daa7-4f97-a34e-58312b3518ec)

**2. Import a SMT-AASX file into AASPE:**
   File -> Open-> Select SMT-AASX file for Handover Documentation V1.2
   This also supports document shelf, handover documentation form and has a semanticId "0173-1#01-AHF578#001".

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/3b8671ee-7e3a-4207-8720-ffe0d0a3169d)

**3. Manually creating the SM**
   Create the SM for Handover Documentation and add a semanticId "0173-1#01-AHF578#001". Save the AASX File. This 
   triggers views document shelf and handover documentation form. 

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/77d3401f-6b03-4271-bee2-da3c1198891a)

In case you are facing the issue apart from above mentioned scenarios, please describe the steps to reproduce in detail.

**Comment by WelliSolutions** [comment]
Thank you. I somehow missed that entry.
