### ISSUE TITLE
Import Thing Description JSON LD document into SubModel failed [BUG]

### ISSUE THREAD

**Issue by STUBA-rupr** [eclipse-aaspe/aaspe#199]
**Unable to import the JSON LD File**
I tried to **Import Thing Description JSON LD document into SubModel**, but it failed with the error **Unable to import the JSON LD File**.  

**To Reproduce**

- You can us an example JSON LD from http://plugfest.thingweb.io/playground/, or generate a new one using https://eclipse.github.io/editdor/.
- Create a new AAS, create a new instance  Submodel e.g. SM1
- Select the SM1 and from File menu go to Import Thing Description JSON LD document into SubModel and select the JSON LD file.
- The action will fail at this point:
![image](https://github.com/eclipse-aaspe/aaspe/assets/55546830/ec14f128-30ab-47cd-b039-da50bca62cca)
(In version V2 same action works).

**Desktop (please complete the following information):**
 - OS: WIN19 Server
 - Commit: Repository updated to commit  23f4aead .

**Comment by juileetikekar** [comment]
The issue has been fixed.
