### ISSUE TITLE
CD's not acessable in AASPE (error when selecting CD) - SMT Time Series Data #59 [BUG]

### ISSUE THREAD

**Issue by foprs** [eclipse-aaspe/aaspe#200]
**Describe the bug**
When clicking on various CD (e.g., RelativeTimePoint) AASPE (version 03/05/2024) throws an error.

File: IDTA 02008-1-1_Template_TimeSeriesData.aasx

**To Reproduce**
1. Load SMT Time Series Data from IDTA
2. Edit / Go to CD -> select RelativeTimePoint

**Expected behavior**
CD is shown

**Screenshots**
![image](https://github.com/eclipse-aaspe/aaspe/assets/118162568/a080ecdd-f6c8-4d28-904f-186e21a67fea)

**Desktop (please complete the following information):**
 - AASPE (version 03/05/2024)

**Additional context**
see also https://github.com/admin-shell-io/submodel-templates/issues/59

**Comment by juileetikekar** [comment]
Hi @foprs,

Recently we have upgraded the submodel templates from V2 to V3. Please try the latest submodel template for time series.

Also, there have been some bug fixes in the latest AASPE. The latest AASPE does not show any issue/exception with the new SMT for time series. 

This I would like to request you to use the latest version of both SMT and AASPE.

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/bdeee71b-05ce-4a1b-9556-b991c05887a6)
