### ISSUE TITLE
"Add Entity" button in Digital Nameplate Viewer is not useful

### ISSUE THREAD

**Issue by WelliSolutions** [eclipse-aaspe/aaspe#23]
**Describe the bug**
Clicking the "Add Entity.." button in the Digital Nameplate Viewer adds a copy of the explanation, but does not add an entity.

**To Reproduce**
1. Open an AASX file which has a digital nameplate
2. Select the digital nameplate viewer in the AASX tree
3. Look at the description below the layout. It starts with (10) ManufacturerProductFamily or ManufacturerProductType and ends with (5) Serial Number
4. Click the "Add Entity.." button
5. The scrollbar gets longer. The descriptions have duplicated. (10) and (5) appear twice

**Expected behavior**
IDK.
Probably a dialog should pop up (because the button has ...).
I imagine that one can select one of the properties of the digital nameplate and that property is then created.

**Screenshots**
![image](https://github.com/eclipse-aaspe/aaspe/assets/14279507/5d66fb62-d389-4b6f-9b0e-eae7a6a2481a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser N/A

**Additional context**
Version 2023-11-17

**Comment by MichaelHoffmeisterFesto** [comment]
Current branch name: MIHO/Post_XMAS2023_Bugfixes

* The button "Add entity .." was copy/paste artifact from anoher plugin. It was useless.
* Clicking the button lead to a un-intended and misbehavin partial update of the plugin panel.
* [deleted] the button.
