### ISSUE TITLE
Migration of open issues

### ISSUE THREAD

**Issue by WelliSolutions** [eclipse-aaspe/aaspe#3]
**Is your feature request related to a problem? Please describe.**
There were several open issues on the [old repo](https://github.com/admin-shell-io/aasx-package-explorer).
Will they be migrated?

**Describe the solution you'd like**
I'd like to see the open issues fixed.

**Describe alternatives you've considered**
I may re-enter all of my issues here. But that's time-consuming manual effort for me.

**Additional context**
None.

**Comment by BirgitBoss** [comment]
Transferring issues between different organizations seems not to be supported by github, see https://github.com/orgs/community/discussions/5766 but there seem to be some script solutions: https://github.com/orgs/community/discussions/5766#discussioncomment-8071245 or https://github.com/orgs/community/discussions/5766#discussioncomment-6067553

**Comment by martafullen** [comment]
We are investigating if it's possible to migrate issues in-bulk with the help of Eclipse. 
In the meantime, another alternative is to use the [GitHub API](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28) in a script to copy the issue contents and paste into a new issue.

**Comment by juileetikekar** [comment]
Hi @WelliSolutions,

All the issues from old GitHub repo of AASPE have been migrated to the new repo. We have started working on them as well.
