### ISSUE TITLE
Contact information viewer creates incorrect Language property

### ISSUE THREAD

**Issue by WelliSolutions** [eclipse-aaspe/aaspe#33]
**Describe the bug**
When specifying languages, the contact information editor creates them as Language{0:00} instead of Language01.

**To Reproduce**
1. Create or open as AAS which has contact information
2. Add a language
    ![image](https://github.com/eclipse-aaspe/aaspe/assets/14279507/af545458-8b1c-401a-8ad3-342c512e9f82)

4. Click "Update to AAS"
5. The property gets creates as Language{0:00}
    ![image](https://github.com/eclipse-aaspe/aaspe/assets/14279507/484e7c9a-fe74-4c02-8161-30b8d5c6b973)

**Expected behavior**
It should be Language01 instead.

**Screenshots**
See repro steps.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser N/A

**Smartphone (please complete the following information):**
None

**Additional context**
None

**Comment by MichaelHoffmeisterFesto** [comment]
Current branch name: MIHO/Post_XMAS2023_Bugfixes

* [changed] .aad.json-options file for ContactInformation (manually)
* export code: AasFormUtils.cs:ExportAsGenericFormsOptions()
* tested

**Comment by MichaelHoffmeisterFesto** [comment]
I think it is closed.
