### ISSUE TITLE
Thumbnail image does not change with selection of a different AAS

### ISSUE THREAD

**Issue by WelliSolutions** [eclipse-aaspe/aaspe#35]
**Describe the bug**
When an AASX file has 2 AAS, Package Explorer always displays the thumbnail of the first AAS.

**To Reproduce**
1. Open the 01_Festo.aasx from the sample AASX files
2. In Edit mode, add a new AAS, add a globalID
3. Switch between the Festo AAS and the new AAS
4. See how the IDs in the graphic change, but the thumbnail picture doesn't

**Expected behavior**
The thumbnail of the selected AAS is displayed. 
No Thumbnail is displayed if the AAS does not have a thumbnail.

**Screenshots**
With Festo selected:
![image](https://github.com/eclipse-aaspe/aaspe/assets/14279507/126e390b-7bf1-490e-ab3d-7272fb473f69)

With the new AAS selected
![image](https://github.com/eclipse-aaspe/aaspe/assets/14279507/4672a7cf-4c56-4907-ba64-b353fa79eb31)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser N/A

**Smartphone (please complete the following information):**
None

**Additional context**
Version 2023-11-17

**Comment by WelliSolutions** [comment]
It seems like Package Explorer shows the first OPC (Open Packaging Conventions) thumbnail image that is described in the `_rels/.rels` file. It does not consider the Identification/Thumbnail (semantic IDs https://www.hsu-hh.de/aut/aas/identification and https://www.hsu-hh.de/aut/aas/thumbnail).

So this issue is probably a feature request rather than a bug.

**Comment by WelliSolutions** [comment]
Let me change my mind again while I'm still learning...
Each AAS has an AssetInformation. AssetInformation may have a DefaultThumbnail resource. Better use that one.

**Comment by MichaelHoffmeisterFesto** [comment]
Hello,
yes, the OPC convention foresees, that there only one thumbnail.
For a thumbnail per AAS, use the AssetInformation/DefaultThumbnail ressource.
For efficiency reasons, the AASX Package Explorer only changes the left-hand display, when the user selects an AAS (not for every sub-ordinate element of the tree).
With the current branch: MIHO/Post_XMAS2023_Bugfixes
I've checked the behaviour and it seems to work as intended: fallback is the OPC thumbnail, the AssetInformation/DefaultThumbnail is dominant (see attached modified AASX).

**Comment by MichaelHoffmeisterFesto** [comment]
I think it is closed.

**Comment by LukasBenner** [comment]
Unfortunately, I can't reproduce the described behavior with the current [release (v2024-06-10)](https://github.com/eclipse-aaspe/package-explorer/releases/tag/v2024-06-10.alpha).

1. Create a new AASX.
2. Add a new AAS.
3. DefaultThumbnail: Create an empty resource element.
4. Upload a file through the supplemental file assistant.
5. Press Ctrl+S (which will cause a very annoying error—why is it so hard to detect that this is an initial save?).
6. No thumbnail is displayed (closing and reopening doesn't help).

![grafik](https://github.com/eclipse-aaspe/package-explorer/assets/36197800/9a91a5b5-b4c4-4668-8d30-3e572c6a4de6)

**Comment by LukasBenner** [comment]
@MichaelHoffmeisterFesto 
As long as this doesn't work in the current release, I wouldn't consider the issue as closed.
