### ISSUE TITLE
XML Export does not work

### ISSUE THREAD

**Issue by ChristopherSchl** [eclipse-aaspe/aaspe#39]
I try to export my AAS as a xml file. I use for that _Export.. -> Export OPC UA nodeset2.xml (via UA server plug-in)_.
But when i try to execute that command I get error that a .dll file "libuv" was not found.

![image](https://user-images.githubusercontent.com/61227854/91957242-0ce2d380-ed06-11ea-9a91-43fc526d4d97.png)

I do not know what to do, with that information or how to fix it. Is there an other way to exort to xml? Or do i need to add a file to be able to do that?

I use the Version 1.9.8.3 from Mon 08/31/2020.

Kind regards
Chris

**Comment by juileetikekar** [comment]
As no more activity, since 2021 closing the issue as of now. If necessary, the issue can be reopened.
