### ISSUE TITLE
Thumbnail per AAS

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-aaspe/aaspe#47]
This is the transfer of issue 
https://github.com/admin-shell/aasx-package-explorer/issues/14
to this repository.

In V3.0RC01 a thumbnail per Asset and thus AAS was introduced.

**Comment by juileetikekar** [comment]
Although AASPE has been upgraded to the metamodel V3, the thumbnails do not change w.r.t. the selection of the AAS, when an AASX file consists of multiple AASs.

Related to #35

**Comment by BirgitBoss** [comment]
Since this is a duplicate to #35 and #35 explains it much better I would close this issue.
