### ISSUE TITLE
Export OPC UA Nodeset2.xml (via UA server plug-in)

### ISSUE THREAD

**Issue by Julpygo** [eclipse-aaspe/aaspe#49]
**Describe the bug**
I want to create a nodeset.xml file to import it into my OPC UA server developed in python, in such a way that it allows me to install an AAS, starting from said file; but I get the following error:
![image](https://user-images.githubusercontent.com/72952395/102244648-8fb12800-3eca-11eb-802e-58177d0c940c.png)
Starting plug-in Net46AasxServerPlugin, action server-start ..
[Net46AasxServerPlugin] Starting OPC UA AASX Server. Based on the OPC Foundation UA Net Standard stack.
[Net46AasxServerPlugin] Copyright (c) 2018-2019 Festo AG & Co. KG <https://www.festo.com/net/de_de/Forms/web/contact_international>, author: Michael Hoffmeister.
[Net46AasxServerPlugin] Portions copyright (c) by OPC Foundation, Inc. and licensed under the Reciprocal Community License (RCL).
[Net46AasxServerPlugin] See https://opcfoundation.org/license/rcl.html.
[Net46AasxServerPlugin] AASX package env has filename C:\Users\Desktop_J_Y\OneDrive - correounivalle.edu.co\Proyecto de grado\AasxPackageExplorer\content-for-demo\Example_AAS_ServoDCMotor_21.aasx
[Net46AasxServerPlugin] Taking over 2 arguments: -export-nodeset C:\Users\Desktop_J_Y\OneDrive - correounivalle.edu.co\Proyecto de grado\Mi_Git_Hub\Industria4.0-Univalle\Impresoras3D_VBS\XML\AAS_ServoDCMotor.xml
[Net46AasxServerPlugin] will start..........
[Net46AasxServerPlugin] [1] Could not load HTTPS Stack Listener. No se puede cargar el archivo DLL 'libuv': No se puede encontrar el módulo especificado. (Excepción de HRESULT: 0x8007007E) AggregateException 'Se han producido uno o varios errores.' Se han producido uno o varios errores.
[Net46AasxServerPlugin] [128] MasterNodeManager.Startup - NodeManagers=3 -
[Net46AasxServerPlugin] [1] Unexpected error starting application ArgumentNullException 'El valor no puede ser nulo.
Nombre del parámetro: server' El valor no puede ser nulo.
Nombre del parámetro: server

**To Reproduce**
1- Download aasx-package-explorer-small.2020-12-03.alpha.rar
2- unzipped the rar
3- I opened aasx package explorer
4- load the aasx of the exampleMotor
5- use the Export Nodeset2 Via OPC UA Server option.
6- Modify the file [NET46AasxServerPlugin.Config.xml], Change the localhost part for my IP address; however the error remains the same.

**Expected behavior**
I was hoping to create an AAS xml file to import into my OPC UA server developed in python; but a file is created that when I import it on the server it doesn't work, I wanted to get an xml file like the following:
![image](https://user-images.githubusercontent.com/72952395/102247413-ed933f00-3ecd-11eb-9b22-3ba96cd29567.png)
![image](https://user-images.githubusercontent.com/72952395/102247483-03a0ff80-3ece-11eb-8c3f-ee09c70ae51c.png)
![image](https://user-images.githubusercontent.com/72952395/102247566-1b788380-3ece-11eb-8019-250f9a76d2e0.png)
![image](https://user-images.githubusercontent.com/72952395/102247622-2af7cc80-3ece-11eb-877c-799c5a37e068.png)
![image](https://user-images.githubusercontent.com/72952395/102247692-4236ba00-3ece-11eb-9eb6-dde523618f26.png)
![image](https://user-images.githubusercontent.com/72952395/102247759-5c709800-3ece-11eb-8fcf-2b430e39c17a.png)

Finally I hope to know if the described option allows me to do what I want, or an explanation of how it is used ... I would appreciate it.

**Comment by juileetikekar** [comment]
As no more activity, since 2020 closing the issue as of now. If necessary, the issue can be reopened.

**Comment by hadifar** [comment]
Same issue! Is it possible to export nodeset XML from package explorer and directly import it to OPCUA python server?

```
import logging
from opcua import Server

logging.basicConfig(level=logging.INFO)
_logger = logging.getLogger('asyncua')


def main():
    server = Server()
    path = "XML_FROM_PACKAGE_EXPLORER_OPCUA_PLUGIN.xml"
    server.import_xml(path)
    server.start()


if __name__ == '__main__':
    main()
```
