### ISSUE TITLE
Icons not shown in Flyover

### ISSUE THREAD

**Issue by MichaelHoffmeisterFesto** [eclipse-aaspe/aaspe#51]
change to "/AasxIntegrationBaseWpf;component/Resources/msg_info.png" an similar
for TextBox, Progressbar

(root cause: moved MessageBox to AasxIntegrationBaseWpf)

**Comment by juileetikekar** [comment]
As no more activity, since 2020 closing the issue as of now. If necessary, the issue can be reopened.
