### ISSUE TITLE
Copy error for AAS copy recursively

### ISSUE THREAD

**Issue by JoMMC** [eclipse-aaspe/aaspe#62]
If you want to copy an AAS recursively, the explorer creates a new entry with the same count of sub models (based on the source AAS) but the addresses and the name is the every time the same.

![grafik](https://user-images.githubusercontent.com/78344087/106460282-64db5d00-6493-11eb-8589-2fbf47122ed7.png)

1. choosing the "Env "AdminstrationShells""
2. Click on 'copy recursively'
3. Select an existing AAS
4. See the incorecct result in the picture

**Expected behavior**
A new entry for an AAS with the same sub model names and different addresses

**Comment by juileetikekar** [comment]
Hi @JoMMC  and @chrweiss,

The issue was not reproduced in the latest version of the AASX Package Explorer.

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/abf49f9b-a868-4e8f-a0a0-0b1c13a64fd1)
