### ISSUE TITLE
Interfacing AAS with asset

### ISSUE THREAD

**Issue by Ayyubshaikh** [eclipse-aaspe/aaspe#63]
Hello guys, does AAS Package explorer have a feature so that i can interface it with the asset(Demonstrators robot) using OPC UA and access the robot.

**Comment by juileetikekar** [comment]
Hi @Ayyubshaikh,

You can use OPC UA plugin of the AASX Package Explorer for this. Also please refer the Asset Interface Description and Asset Interface Mapping Configuration Submodel Templates published by IDTA for the same.
