### ISSUE TITLE
Readme: there is no chapter "Get started" - "Quick Start"?

### ISSUE THREAD

**Issue by BirgitBoss** [eclipse-aaspe/aaspe#68]
Source: readme.md

In Contributing section, the guide is "If you want to contribute in code, see Section "**Getting started**"."

I assume "Getting started" was renamed to "**Quick Start**" and this is the section you are referring to? At least I do not find a section "Getting started".

**Comment by juileetikekar** [comment]
Hi @BirgitBoss,

Please find the updated contributing guidelines at https://github.com/eclipse-aaspe/aaspe/blob/main/CONTRIBUTING.md.
