### ISSUE TITLE
Plugins do not show in AASX

### ISSUE THREAD

**Issue by MMFB65** [eclipse-aaspe/aaspe#69]
Hello,

I can see the list of plugins in its folder when I download the zip file.
But, when I open the AASX explorer, I cannot see the exact list. I see only some of plugins.

Would you please let me know if I need to fix something?

Bests,
Mahdi

**Comment by juileetikekar** [comment]
Hi @MMFB65 and @lenaxus,

one way to use the plugins is as below:

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/b1445294-fc2b-4cc0-b933-15c7f29c281c)

You can also refer "options-debug.json" file from the extracted zip file of the doenload of AASPE, which provides a list of enabled plugins.

The third option is to check the logs, which talks about theloading of the plugin.
