### ISSUE TITLE
Package Explorer: Import of a sub model

### ISSUE THREAD

**Issue by JoMMC** [eclipse-aaspe/aaspe#71]
How can I import a sub model into a open AASX file?
Which format works (JSON, CSV,...)?
May I have a template (JSON-structure, CSV-file)?
Thanks

**Comment by juileetikekar** [comment]
Hi @JoMMC,

The above hint must have answered your query. If you have further questions, please feel free to reopen the issue.

Also, please try the latest version of the AASX Package Explorer, which also supports V3 version of the AAS Metamodel.
