### ISSUE TITLE
Display of Submodels in a XML-file which are not defined by local=true in the Reference is missing

### ISSUE THREAD

**Issue by TorbenD** [eclipse-aaspe/aaspe#74]
We tried to read our example xml files with the aasx package explorer but it does not work correctly. It only shows the AAS but not the Submodels. The error report gives no concrete message only, that the references to the submodels are missing. We checked our file and do not find any problems.

Here is the link to our file:
https://git.rwth-aachen.de/acplt/pyi40aas/-/blob/master/test/compliance_tool/files/test_demo_full_example.xml

Here is screenshot of the aasx package explorer with the loaded xml file:
[![image](https://user-images.githubusercontent.com/19833045/115689724-a4139e80-a35c-11eb-9c3c-35cc66097648.png)](url)

**Comment by juileetikekar** [comment]
Hi @TorbenD,

Please try the latest version of the package explorer, which now supports V3 version of the AAS Metamodel. In this V3 version, the "local" is no more used.

The file provided in the decription, opened in V3 AASPE.
![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/a8c39d1e-72ad-4fc8-9ae0-d7db178532af)
