### ISSUE TITLE
Inconsistency in OperationVariable Handling with Specification

### ISSUE THREAD

**Issue by FrankSchnicke** [eclipse-aaspe/aaspe#78]
The generated XML in the AASX for operations is missing the operationVariable tag level.
Right now, it is  
![image](https://user-images.githubusercontent.com/77283144/121524339-81664380-c9f7-11eb-9f0f-d4129b22041f.png)

but it should be 
![image](https://user-images.githubusercontent.com/77283144/121524263-6dbadd00-c9f7-11eb-9c77-316422860d73.png)

as also described on p. 211 DotAAS Part 1 V2.0.1.

**Comment by juileetikekar** [comment]
Hi @FrankSchnicke,

In the latest version of the AASPE, the serialization of the operation SME is as below:

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/27a8dc10-8387-4c9c-8477-2676b47ad25c)
