### ISSUE TITLE
Mac Os or Linux installation ? 

### ISSUE THREAD

**Issue by felipeinfantino** [eclipse-aaspe/aaspe#79]
Can this be installed on Mac Os Mojave or on any Linux distro?

If so, could you please provide installation steps?

**Comment by juileetikekar** [comment]
Hi All,

Please use the latest version of the AASX Package Explorer, which is also now available in Blazor Explorer format.

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/c01eb765-2bd6-43aa-bb34-d043b530f34b)

**Comment by NunoSav** [comment]
@atextor were you able to get it to work?
