### ISSUE TITLE
Spec V3.x support in the PackageExplorer?

### ISSUE THREAD

**Issue by charithmu** [eclipse-aaspe/aaspe#81]
Hello,

What is the AAS spec version currently used in the package explorer? Are there any plans/ current work in progress to support V3.x?
Does the export JSON function uses this spec or something else? @mristin 

Thanks.

**Comment by juileetikekar** [comment]
Hi @charithmu, @hmrc87, @bs-jokri,

The V3 version of the AASX Package Explorer is now available.
