### ISSUE TITLE
Unable to import Submodels/SubModelElements exported from iec-cdd

### ISSUE THREAD

**Issue by kapilbhudhia** [eclipse-aaspe/aaspe#84]
I am not able to import the submodels/submodelelements exported from the iec-cdd website as explained in the following screen cast : https://admin-shell-io.com/screencasts/aasx-package-explorer/en/Aasx_PackEx_Tutorial_-_EN_-_52_Import_IEC_CDD_Class_Export.mp4.

I have made sure to copy the xls files into the iec-cdd subdirectory under the AasxPackageExplorer directory. 
![image](https://user-images.githubusercontent.com/5068272/130586750-0de6dcee-28e2-4a41-b28d-443848cffadf.png)

When trying to import the Submodel no options are provided in the drop down (check image). 
![image](https://user-images.githubusercontent.com/5068272/130587124-e489c675-823d-4949-81eb-aa13ec1573f1.png)

Even manually choosing the xls file makes no difference.

I am using the following version of the AASX package explorer
![image](https://user-images.githubusercontent.com/5068272/130587422-ae2d61d7-69c8-429b-a3eb-af8a57f3aaa6.png)

**Comment by juileetikekar** [comment]
Hi @kapilbhudhia,

We hope the hints provided above must have helped you. We would also like to request you to try the latest version of the AASX Package Explorer, which now also supports V3 version of the AAS Metamodel.
