### ISSUE TITLE
MQTT Plugin

### ISSUE THREAD

**Issue by ferremientos** [eclipse-aaspe/aaspe#85]
**Describe the bug**
Hi,

I want to use the MQTT Plugin with the AASx Package Explorer. 

When I try to use the cmd line to enable the plugin with " C:\user....\AasxPackageExplorer -dll AasxMqttServer.dll" or " C:\user....\AasxPackageExplorer -dll AasxMqtt\bin\Debug\AasxMqttServer.dll", it doesn't work. 

It just open the AASx Package Explorer again.

I appreciate if you can help with this problem.

Thank you!
Ferremientos

**Comment by juileetikekar** [comment]
Hi @ferremientos,

We hope the information provided above has helped you solve the issue. Please reopen the issue, if you face it again.
