### ISSUE TITLE
Edit of File element / Select file shows no file name

### ISSUE THREAD

**Issue by MichaelHoffmeisterFesto** [eclipse-aaspe/aaspe#88]
Select file by file dialogue
"Source file to add:" should show filename -> nothing

**Comment by juileetikekar** [comment]
Hi @MichaelHoffmeisterFesto,

The issue has been fixed in the latest version of the AASX Package Explorer !!

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/fc9661eb-75ed-4421-94e9-1cb9d0cffe1c)
