### ISSUE TITLE
JSON Array in AASX Explorer

### ISSUE THREAD

**Issue by adwaitchuri** [eclipse-aaspe/aaspe#90]
I don't see an option to create JSON Array for SubModel, Collection or Property.
The structure I am looking for is attached. 
[DefectList_Put_Request_Body.txt](https://github.com/admin-shell-io/aasx-package-explorer/files/7571050/DefectList_Put_Request_Body.txt)

I tried using the options - "ordered": true, and "allowDuplicates": true,
Kindly do let know, what are the ways using which this requirement can be fulfilled?

**Comment by juileetikekar** [comment]
Hi @adwaitchuri,

In the latest version of the AAS Metamodel, there is a possibility to model a SubmodelElementCollection and a SubmodelElementList. Please refer section 5.3.7.16 and 5.3.7.17 from https://industrialdigitaltwin.org/wp-content/uploads/2023/06/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf for more details.
