### ISSUE TITLE
valueType --> Data type not following spec?

### ISSUE THREAD

**Issue by janfelixklein** [eclipse-aaspe/aaspe#91]
Hello,

today I was trying to use the `Example_AAS_ServoDCMotor_21.xml` generated by the AASX-Explorer in the PyI40AAS Python implementation and came across the following problem:

`ValueError: aas:valueType on line 108 has invalid text: langString`

This is e.g. part of the Property-Submodelelement "ProductDesignation".
![grafik](https://user-images.githubusercontent.com/47968254/144589932-9d451990-0cfc-4663-b494-ba2da4903558.png)

![grafik](https://user-images.githubusercontent.com/47968254/144590022-a950f02c-b64e-452b-a6c2-d9b4ef481916.png)

The error basically states that langString is an invalid DataType to be used for the valueType attribute. And this seems to be in fact true when taking a look at the spec:

valueType has Type "DataTypeDef"
![grafik](https://user-images.githubusercontent.com/47968254/144590431-440ad21d-92e9-4cf6-a30c-e6e1244893f0.png)

and should be any xsd simple type which does not include langString
![grafik](https://user-images.githubusercontent.com/47968254/144590955-0938855f-9a57-4d80-8e75-e51b07e4a988.png)

 However, the AASX Explorer allows to select langString as an valueType and might therfore not be in line with the spec.

**Comment by juileetikekar** [comment]
Hi @janfelixklein,

The latest version of the AASX Package Explorer now supports V3 version of the AAS Metamodel. In this version, the valueType is now enumerated as shown in the screenshot:

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/5e9e9e62-7ddb-4f17-a375-928bd255f1b9)
