### ISSUE TITLE
Enable SubmodelElementCollections in Operations to be adjustable

### ISSUE THREAD

**Issue by FischerRene** [eclipse-aaspe/aaspe#96]
**Is your feature request related to a problem? Please describe.**
Creating an Operations with a SubmodelCollection as in-/ouptut value does not allow any adjustments of its properties. The SMC only has a name and information on how many elements it contains.
As soon as you want to add a SubmodelElement the focus gets shifted to the "Package" and the new element is plain.

**Describe the solution you'd like**
Add a recursive drop down menu for every SMC as part of operations.
(Like it is for SMCs outside the Operation.)

**Describe alternatives you've considered**
If I want to add or review information of those variables, I have to add them one by one, which adds to the complexity and seems chaotic.

**Comment by juileetikekar** [comment]
Hi @FischerRene,

The issue is not reproducible in the latest version of the AASX Package Explorer, which now also supports the V3 version of the AAS Metamodel.

![image](https://github.com/eclipse-aaspe/aaspe/assets/99317579/704db46a-91aa-41d3-b3be-134317d759e7)
